// scripts/compile-views.js
// Compiles all .ejs templates in the views/ directory into pure JavaScript functions
// ahead-of-time so they can run securely in Cloudflare Workers without eval() / new Function().

const fs = require('fs');
const path = require('path');
const ejs = require('ejs');

const viewsDir = path.join(__dirname, '..', 'views');
const outputFile = path.join(__dirname, '..', 'views-compiled.js');

function getEjsFiles(dir) {
  let files = [];
  const items = fs.readdirSync(dir);
  for (const item of items) {
    const full = path.join(dir, item);
    const stat = fs.statSync(full);
    if (stat.isDirectory()) {
      files = files.concat(getEjsFiles(full));
    } else if (item.endsWith('.ejs')) {
      files.push(full);
    }
  }
  return files;
}

const ejsFiles = getEjsFiles(viewsDir);
const compiledEntries = [];

const allLocals = [
  'currentUser',
  'user',
  'error',
  'success',
  'assets',
  'asset',
  'equipment',
  'requests',
  'request',
  'stats',
  'recentRequests',
  'recentMaintenance',
  'maintenanceLogs',
  'logs',
  'log',
  'isEdit',
  'action',
  'title',
  'search',
  'category',
  'condition',
  'status',
  'formData',
  'message',
  'damagedOrLostAssets',
  'damagedOrLostCount',
  'damagedOrLostReturns',
  'overdueCount',
  'overdueRequests',
  'totalAssets',
  'totalAvailableUnits',
  'totalIssuedUnits',
  'currentFilter',
  'isStaffView',
  'cost',
  'serviceDate',
  'nextServiceDue',
  'notes'
];


for (const filePath of ejsFiles) {
  const relPath = path.relative(viewsDir, filePath).replace(/\\/g, '/');
  const key = relPath.replace(/\.ejs$/, '');
  const content = fs.readFileSync(filePath, 'utf8');
  const fn = ejs.compile(content, { 
    client: true, 
    compileDebug: false,
    _with: false,
    destructuredLocals: allLocals
  });
  compiledEntries.push(`  ${JSON.stringify(key)}: ${fn.toString()}`);
}

const fileContent = `// Auto-generated by scripts/compile-views.js
// Ahead-of-time compiled EJS templates for Cloudflare Workers compatibility.
// Uses strict mode and destructuredLocals (no eval, no with statement).

module.exports = {
${compiledEntries.join(',\n\n')}
};
`;

fs.writeFileSync(outputFile, fileContent, 'utf8');
console.log(`Successfully compiled ${ejsFiles.length} EJS templates to ${outputFile}`);

